In [4]:
# Import modules
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import dask.dataframe as dd
import gc

In [5]:
df = pd.read_csv("Resources/2.1filtered-data.csv")

In [6]:
df

,cells,FAM138A,OR4F5,OR4F29,OR4F16,FAM87B,LINC00115,FAM41C,SAMD11,NOC2L,...,MCM3AP,YBEY,C21orf58,PCNT,DIP2A,S100B,PRMT2,MAFIP,FAM231C,cells 2
0,ACAGCTAAGGGTTCCC,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ACAGCTAAGGGTTCCC
1,ACATACGTCATTTGGG,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ACATACGTCATTTGGG
2,ACATCAGAGTCGTACT,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ACATCAGAGTCGTACT
3,AGAGTGGGTGCAACTT,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AGAGTGGGTGCAACTT
4,AGGCCACGTTCGCGAC,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AGGCCACGTTCGCGAC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12336,TGCTACCTCTCGCATC,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TGCTACCTCTCGCATC
12337,TGGCTGGTCGGTGTTA,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TGGCTGGTCGGTGTTA
12338,TTAGGACTCCACGACG,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TTAGGACTCCACGACG
12339,TTGGAACGTCCCTTGT,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TTGGAACGTCCCTTGT
12340,TTTACTGCATCCCACT,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TTTACTGCATCCCACT

In [32]:
# # Move 'col1' and 'col2' to the beginning of the DataFrame
# cols = ['cells'] + [col for col in df.columns if col not in ['cells']]
# # df = df.drop('cells 2', axis=1)


# # Move 'cells' column to the beginning
# df = df[['cells'] + [col for col in df.columns if col != 'cells']]

In [36]:
df.columns

Index(['cells', 'FAM138A', 'OR4F5', 'OR4F29', 'OR4F16', 'FAM87B', 'LINC00115',
       'FAM41C', 'SAMD11', 'NOC2L',
       ...
       'MCM3AP', 'YBEY', 'C21orf58', 'PCNT', 'DIP2A', 'S100B', 'PRMT2',
       'MAFIP', 'FAM231C', 'cells 2'],
      dtype='object', length=21454)

In [49]:
# Save the DataFrame to a CSV file without the index
df.to_csv("Resources/2.1filtered-data.csv", index=False)

In [50]:
import pandas as pd

chunk_size = 10000  # Number of rows to read at a time (you can adjust this based on memory capacity)
chunk_iter = pd.read_csv('Resources/2.1filtered-data.csv', chunksize=chunk_size)

# Example: Processing the first chunk
for chunk in chunk_iter:
    # Perform your EDA here, e.g., calculating summary statistics or visualizing data
    chunk.head()  # Display the first few rows of the chunk

In [43]:
# #Merge clean datasets
# # Load the datasets
# df1 = pd.read_csv("2.1filtered-data.csv")
# df2 = pd.read_csv("1.0df_renamed.csv")

# # Merge on a common column (replace 'id' with the actual column name)
# df_merged = pd.merge(df1, df2, on='id', how='inner')  # Use 'left', 'right', or 'outer' if needed

# # Drop the 'cells 2' column from the merged dataset
# df_merged = df_merged.drop(columns=["cells 2"])

# # Save the merged dataset
# df_merged.to_csv("3.0merged_dataset.csv", index=False)
# df_merged