In [6]:
# Import modules
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import dask.dataframe as dd
import gc

In [7]:

# Set the chunk size for reading the data, adjusting based on memory availability
chunk_size = 10000  # Each chunk will have up to 10,000 rows, you can adjust this as needed

# Initialize an empty list to store the processed chunks
dfs = []  # This will hold each chunk of the DataFrame after processing

# Read the large TSV file in chunks to avoid memory issues
for chunk in pd.read_csv('GSE139495_Single_cell_Raw_counts_10252019.tsv', sep="\t", index_col=0, chunksize=chunk_size):
    # Process each chunk by converting its data to a smaller data type to reduce memory usage
    chunk = chunk.astype('float32')  # Convert the data type of each column to 'float32'
    
    # Append the processed chunk to the list of DataFrame chunks
    dfs.append(chunk)  # Each chunk is added to the 'dfs' list

# Combine all the processed chunks into a single DataFrame
df2 = pd.concat(dfs)  # Concatenate all the chunks together into one DataFrame

In [9]:
# Display summary information about the DataFrame 'df2'
# This will show the number of non-null entries, data types, and memory usage
df2.info()

# Display the first 10 rows of the DataFrame 'df2'
# This will help you inspect the first few records in the DataFrame to ensure it's loaded correctly
df2.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 33538 entries, MIR1302-2HG to FAM231C
Columns: 12341 entries, ACAGCTAAGGGTTCCC to TTTACTGCATCCCACT
dtypes: float32(12341)
memory usage: 1.5+ GB

,ACAGCTAAGGGTTCCC,ACATACGTCATTTGGG,ACATCAGAGTCGTACT,AGAGTGGGTGCAACTT,AGGCCACGTTCGCGAC,AGTGGGACATCCGGGT,ATCACGAGTCCAGTTA,ATCATGGGTCCGACGT,ATTACTCCAGATCTGT,CAAGATCGTCCATCCT,...,TCGGGACAGGACTGGT,TCTATTGAGCCTCGTG,TCTTTCCAGTCTTGCA,TGCCAAAAGCGTCAAG,TGCGGGTTCCTCATTA,TGCTACCTCTCGCATC,TGGCTGGTCGGTGTTA,TTAGGACTCCACGACG,TTGGAACGTCCCTTGT,TTTACTGCATCCCACT
MIR1302-2HG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
FAM138A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
OR4F5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL627309.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL627309.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL627309.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL627309.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL732372.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
OR4F29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AC114498.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
# Display summary information about the DataFrame 'df2'
# This will show details such as the number of rows, non-null entries, column data types, and memory usage
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33538 entries, MIR1302-2HG to FAM231C
Columns: 12341 entries, ACAGCTAAGGGTTCCC to TTTACTGCATCCCACT
dtypes: float32(12341)
memory usage: 1.5+ GB

In [13]:
# Display the data types of each column in the DataFrame 'df2'
# This will return the data type of every column, which helps in understanding the structure of the data
df2.dtypes

ACAGCTAAGGGTTCCC    float32
ACATACGTCATTTGGG    float32
ACATCAGAGTCGTACT    float32
AGAGTGGGTGCAACTT    float32
AGGCCACGTTCGCGAC    float32
                     ...
TGCTACCTCTCGCATC    float32
TGGCTGGTCGGTGTTA    float32
TTAGGACTCCACGACG    float32
TTGGAACGTCCCTTGT    float32
TTTACTGCATCCCACT    float32
Length: 12341, dtype: object

# Change the file format from tsv to parquet

In [17]:
# Save the DataFrame 'df2' to a Parquet file named 'data.parquet'
# Parquet is an efficient file format for storing large datasets. 
# Compression with the "snappy" algorithm helps reduce the file size without losing performance
df2.to_parquet("2.0data.parquet", compression="snappy")

In [19]:
import pandas as pd

# Define a function to optimize the data types
def optimize_dtypes(df2):
    optimized_dtypes = {}
    
    for column in df2.columns:
        if df2[column].dtype == 'float64':  # If the column is float64, use float32 to save memory
            optimized_dtypes[column] = 'float32'
        elif df2[column].dtype == 'int64':  # If the column is int64, use int32 to save memory
            optimized_dtypes[column] = 'int32'
        elif df2[column].dtype == 'object':  # If the column is object (strings), we leave it as is or convert to category
            optimized_dtypes[column] = 'category'  # Converting string columns to 'category' saves memory
            
    return optimized_dtypes

# Read the dataset with optimized dtypes
optimized_dtypes = optimize_dtypes(pd.read_parquet("data.parquet"))
df2_clean = pd.read_parquet("data.parquet")

# Display the first few rows to confirm
df2_clean.head()

,ACAGCTAAGGGTTCCC,ACATACGTCATTTGGG,ACATCAGAGTCGTACT,AGAGTGGGTGCAACTT,AGGCCACGTTCGCGAC,AGTGGGACATCCGGGT,ATCACGAGTCCAGTTA,ATCATGGGTCCGACGT,ATTACTCCAGATCTGT,CAAGATCGTCCATCCT,...,TCGGGACAGGACTGGT,TCTATTGAGCCTCGTG,TCTTTCCAGTCTTGCA,TGCCAAAAGCGTCAAG,TGCGGGTTCCTCATTA,TGCTACCTCTCGCATC,TGGCTGGTCGGTGTTA,TTAGGACTCCACGACG,TTGGAACGTCCCTTGT,TTTACTGCATCCCACT
MIR1302-2HG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
FAM138A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
OR4F5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL627309.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL627309.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
# # # Define the file path
# file_path = "data.parquet"  # Update with the correct path if needed

# # # Load the TSV file into a DataFrame
# # df2 = pd.read_csv(file_path, sep="\t", index_col=0)  # Use index_col=0 if the first column contains gene names

# # # Display basic info and the first few rows
# # #df2.head(10)  # Show first few rows

In [23]:
# import pandas as pd

# # Load the Parquet file
# df2 = pd.read_parquet("C:/Users/fjrui/OneDrive/Documents/Desktop/Bootcamp/Project 4/Team_BioByte/Capstone/data.parquet")

# # Display the first few rows
# df2.head(20)

In [24]:
# Get the number of rows (entries) in the DataFrame 'df2'
# This will return the total count of rows in df2
len(df2)

33538

In [27]:
# Display the column names of the DataFrame 'df2'
# This will return a list of all the column names, helping you understand the structure of the DataFrame
df2.columns

Index(['ACAGCTAAGGGTTCCC', 'ACATACGTCATTTGGG', 'ACATCAGAGTCGTACT',
       'AGAGTGGGTGCAACTT', 'AGGCCACGTTCGCGAC', 'AGTGGGACATCCGGGT',
       'ATCACGAGTCCAGTTA', 'ATCATGGGTCCGACGT', 'ATTACTCCAGATCTGT',
       'CAAGATCGTCCATCCT',
       ...
       'TCGGGACAGGACTGGT', 'TCTATTGAGCCTCGTG', 'TCTTTCCAGTCTTGCA',
       'TGCCAAAAGCGTCAAG', 'TGCGGGTTCCTCATTA', 'TGCTACCTCTCGCATC',
       'TGGCTGGTCGGTGTTA', 'TTAGGACTCCACGACG', 'TTGGAACGTCCCTTGT',
       'TTTACTGCATCCCACT'],
      dtype='object', length=12341)

In [29]:
# Get the index values of the DataFrame 'df2'
# This will return the index (row labels) of the DataFrame, which may be integers, strings, or other types
index_values = df2.index

# Display the index values
index_values

Index(['MIR1302-2HG', 'FAM138A', 'OR4F5', 'AL627309.1', 'AL627309.3',
       'AL627309.2', 'AL627309.4', 'AL732372.1', 'OR4F29', 'AC114498.1',
       ...
       'AC007325.2', 'BX072566.1', 'AL354822.1', 'AC023491.2', 'AC004556.1',
       'AC233755.2', 'AC233755.1', 'AC240274.1', 'AC213203.1', 'FAM231C'],
      dtype='object', length=33538)

In [37]:
# Convert the index values of the DataFrame 'df2' into a list
# This allows you to work with the index as a regular Python list rather than a pandas index object
index_list = df2_clean.index.tolist()

# Print only the first 10 values from the index list
# This is useful for inspecting the first few index labels to ensure they're as expected
print(index_list[:10])

['MIR1302-2HG', 'FAM138A', 'OR4F5', 'AL627309.1', 'AL627309.3', 'AL627309.2', 'AL627309.4', 'AL732372.1', 'OR4F29', 'AC114498.1']

In [39]:
# Sample DataFrame
# Create a new DataFrame 'df2_clean' from 'df2'
# This is useful if you want to perform additional operations or transformations on a copy of 'df2'
df2_clean = pd.DataFrame(df2)

# Create a new column "Gen" with the index values
# This adds a new column 'Gen' to 'df2_clean', containing the index values of the DataFrame
df2_clean['Gen'] = df2.index

# Reset the index to create a new index column
# This replaces the existing index with a default integer index and keeps the original index as a column (not dropped)
df2_clean = df2.reset_index(drop=False)

# Display the modified DataFrame
df2_clean

,index,ACAGCTAAGGGTTCCC,ACATACGTCATTTGGG,ACATCAGAGTCGTACT,AGAGTGGGTGCAACTT,AGGCCACGTTCGCGAC,AGTGGGACATCCGGGT,ATCACGAGTCCAGTTA,ATCATGGGTCCGACGT,ATTACTCCAGATCTGT,...,TCGGGACAGGACTGGT,TCTATTGAGCCTCGTG,TCTTTCCAGTCTTGCA,TGCCAAAAGCGTCAAG,TGCGGGTTCCTCATTA,TGCTACCTCTCGCATC,TGGCTGGTCGGTGTTA,TTAGGACTCCACGACG,TTGGAACGTCCCTTGT,TTTACTGCATCCCACT
0,MIR1302-2HG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,FAM138A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,OR4F5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AL627309.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AL627309.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33533,AC233755.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33534,AC233755.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33535,AC240274.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33536,AC213203.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33537,FAM231C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [84]:
# Get the count of each unique value in the "index" column of 'df2_clean'
# This will return the number of times each unique index value appears in the "index" column
df2_clean["index"].value_counts()

index
MIR1302-2HG    1
DCT            1
GPC6-AS2       1
GPC6           1
AL354811.1     1
              ..
ORC3           1
RARS2          1
SLC35A1        1
AL049697.1     1
FAM231C        1
Name: count, Length: 33538, dtype: int64

In [106]:
# Count the occurrences of each unique value in the "index" column of 'df2_clean'
# Then, sort the counts in ascending order to see the least frequent values at the top
cell_counts = df2_clean["index"].value_counts().sort_values(ascending=True)

# Display the sorted counts
cell_counts

index
MIR1302-2HG    1
AL627309.2     1
AL627309.4     1
AL732372.1     1
OR4F29         1
              ..
AC213203.1     1
MT-ND6         1
DNMT3L         1
MT-ND4L        1
FAM231C        1
Name: count, Length: 33538, dtype: int64

In [108]:
# Assuming 'df' is your DataFrame and the column you're interested in is named 'patient'
value_counts = df2_clean['index'].value_counts()

# Filter for values that have only one occurrence
values_with_one_count = value_counts[value_counts == 1]

# Print or return the values that occur exactly once
values_with_one_count

index
MIR1302-2HG    1
DCT            1
GPC6-AS2       1
GPC6           1
AL354811.1     1
              ..
ORC3           1
RARS2          1
SLC35A1        1
AL049697.1     1
FAM231C        1
Name: count, Length: 33538, dtype: int64

In [109]:
# # Assuming 'df2_clean' is your original DataFrame
# new_df = df2_clean[df2_clean.index == 0]

# # Display the new dataset
# new_df

In [112]:
# Set the 'index' column as the new index for the DataFrame and transpose the DataFrame
# The '.T' transposes the DataFrame, converting rows into columns and vice versa
# The '.astype(int)' converts all the values in the DataFrame to integers
df_transposed = df2_clean.set_index('index').T.astype(int)

# Display the transposed DataFrame
df_transposed

index,MIR1302-2HG,FAM138A,OR4F5,AL627309.1,AL627309.3,AL627309.2,AL627309.4,AL732372.1,OR4F29,AC114498.1,...,AC007325.2,BX072566.1,AL354822.1,AC023491.2,AC004556.1,AC233755.2,AC233755.1,AC240274.1,AC213203.1,FAM231C
ACAGCTAAGGGTTCCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACATACGTCATTTGGG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACATCAGAGTCGTACT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGAGTGGGTGCAACTT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGGCCACGTTCGCGAC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGCTACCTCTCGCATC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TGGCTGGTCGGTGTTA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTAGGACTCCACGACG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTGGAACGTCCCTTGT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTACTGCATCCCACT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [114]:
# Filter columns in 'df_transposed' where the column names do not contain a period (.) or hyphen (-)
# The '~' operator negates the condition, so we select columns where the name does not match the pattern
filtered_data_df = df_transposed.loc[:, ~df_transposed.columns.str.contains(r'[.-]')]

# Display the filtered DataFrame
filtered_data_df

index,FAM138A,OR4F5,OR4F29,OR4F16,FAM87B,LINC00115,FAM41C,SAMD11,NOC2L,KLHL17,...,LSS,MCM3AP,YBEY,C21orf58,PCNT,DIP2A,S100B,PRMT2,MAFIP,FAM231C
ACAGCTAAGGGTTCCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACATACGTCATTTGGG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACATCAGAGTCGTACT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGAGTGGGTGCAACTT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGGCCACGTTCGCGAC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGCTACCTCTCGCATC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TGGCTGGTCGGTGTTA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTAGGACTCCACGACG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTGGAACGTCCCTTGT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTACTGCATCCCACT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [116]:
# # Display the column names of the filtered DataFrame 'filtered_data_df'
# # This will return a list of all the column names, helping you understand the structure of the filtered DataFrame
# filtered_data_df.columns
# #

In [118]:
filtered_data_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12341 entries, ACAGCTAAGGGTTCCC to TTTACTGCATCCCACT
Columns: 21452 entries, FAM138A to FAM231C
dtypes: int32(21452)
memory usage: 1010.0+ MB

In [124]:
filtered_data_df.dtypes

index
FAM138A     int32
OR4F5       int32
OR4F29      int32
OR4F16      int32
FAM87B      int32
            ...
PRMT2       int32
MAFIP       int32
FAM231C     int32
cells      object
cells 2    object
Length: 21454, dtype: object

In [ ]:
# Save the DataFrame as a CSV file
filtered_data_df.to_csv('2.0filtered_data.csv', index=False)

# Confirm that the file is saved
print("File saved as '2.0filtered_data.csv'")

-----------------------

In [25]:
# import pandas as pd
# import pyarrow.parquet as pq

# # Function to process the data in chunks
# def find_values_equals_one_parquet(file_path, chunk_size=50000):
#     # Load the parquet file using pandas
#     df = pd.read_parquet(file_path)
    
#     # Iterate over the dataframe in chunks
#     num_chunks = len(df) // chunk_size  # Determine how many chunks we need
#     for chunk_idx in range(num_chunks + 1):  # Include the last partial chunk
#         chunk = df[chunk_idx * chunk_size : (chunk_idx + 1) * chunk_size]
        
#         # Iterate over each column to find where the values are equal to 1
#         for column in chunk.columns:
#             mask = chunk[column] == 1  # Apply condition column by column
            
#             # Extract rows where the value is 1
#             result = chunk[mask]
            
#             # If any rows match, yield the index and column name
#             if not result.empty:
#                 yield result.index, column

# # Specify your Parquet file path
# file_path = r"C:\Users\fjrui\OneDrive\Documents\Desktop\Bootcamp\Project 4\Team_BioByte\Capstone\data.parquet"

# # Use the function to process and find 1's in the dataset
# for index, column in find_values_equals_one_parquet(file_path):
#     print(f"Found value 1 at index: {index} in column: {column}")